### PR TITLE
New documentation

### PR DESCRIPTION
**Pull request by rmenai**
Updated the documentation and added the MIT license

### CODE REVIEW

**Comment by justintime4tea** [comment]
I think we were still discussing the license on this. I advocated for GPL however Mario is advocating for MIT. Let's continue the conversation here and come to consensus before we official "license" the software.

**Comment by rmenai** [comment]
Ok so ill remove the license part and just leave the documentation

**Comment by tranpeter08** [comment]
Having briefly read a few articles and videos between GPL and MIT licenses, I'm on the GPL camp.  If someone uses our source code and makes modifications and redistributes, it should be available to all.

**Comment by newguid0** [comment]
I am a fan of MIT because I dont like to force anybody to open source the code if they dont want.
Since I did not contribute yet, it is ok that my vote has not as much weight as from the creator or contributors.

**Comment by justintime4tea** [comment]
I'm of the GPL camp as well. If you make a derivative of our work, or change it in some way, I believe we are entitled, as well as anyone else who is interested in the project, to have the opportunity to receive those changes, improvements, and or additional features.

If someone wants to make use of our work, without contributing back, there is no reason they cannot separate it from their own work in such a way that allows them to choose their own license for their own work.  I would be happy to go over that with someone so they can enjoy both the benefit of using our work as well as having the freedom to choose their own license.

**Comment by rmenai** [comment]
Ye I removed the license so you can merge it

**Review by justintime4tea — APPROVED** [review]
This looks awesome; thanks for the contribution!

**Comment by MarioDev666** [comment]
Hey, sorry for my late reply. Been busy moving. I ll just be lazy and copy my discord message from a couple of days ago explaining my Vote for MIT :)

Disclaimer: This is only my personal opinion, not a lawyer, not legal advice, not a personal attack on anyone :slight_smile:
I say MIT for the win. I am also strongly against GPL as i don't like forcing developers/startups to open source what they work on if they don't want to. If i decide to open source my code on github then i have already made the decision to make it public domain and therefor have no right to tell people how to use it. If i want that level of control, then i should not be open sourcing my code in the first place.
Another argument against GPL in my opinion is, as developers, a lot of our solutions/methods are taking from other's contributions on the internet (think stackoverflow, coding articles, tutorials, etc). So these people gave their code for free and under a "do whatever you want" license (MIT/Apache). Therefor i have no right to take that code and put it under a "do what i want you to do" licences (GPL).
And off course, MIT/Apache means more adoption and exposure which i think is good for the MM community.

**Pull request merged**
